#!/usr/bin/env python3
"""Formant-synthesize a short cat meow (8-bit PCM) for app_tone_meow.inc."""
import math
import os
import wave

FS = 16000
DUR = 0.46
N = int(FS * DUR)


def clamp01(t):
    if t < 0.0:
        return 0.0
    if t > 1.0:
        return 1.0
    return t


def lerp(a, b, t):
    t = clamp01(t)
    return a + (b - a) * t


def smooth(t):
    t = clamp01(t)
    return t * t * (3.0 - 2.0 * t)


def seq(t, keys):
    if t <= keys[0][0]:
        return keys[0][1]
    for i in range(1, len(keys)):
        t0, v0 = keys[i - 1]
        t1, v1 = keys[i]
        if t <= t1:
            return lerp(v0, v1, smooth((t - t0) / (t1 - t0)))
    return keys[-1][1]


class Pole2:
    def __init__(self):
        self.y1 = 0.0
        self.y2 = 0.0
        self.a1 = 0.0
        self.a2 = 0.0
        self.g = 0.0

    def tune(self, freq, bw):
        w = 2.0 * math.pi * freq / FS
        r = math.exp(-math.pi * bw / FS)
        self.a1 = 2.0 * r * math.cos(w)
        self.a2 = -r * r
        self.g = 1.0 - r

    def tick(self, x):
        y = self.g * x + self.a1 * self.y1 + self.a2 * self.y2
        self.y2 = self.y1
        self.y1 = y
        return y


def rng_step(s):
    s ^= (s << 13) & 0xFFFFFFFF
    s ^= (s >> 17) & 0xFFFFFFFF
    s ^= (s << 5) & 0xFFFFFFFF
    return s & 0xFFFFFFFF


def f0_at(t):
    if t < 0.15:
        return seq(t, [(0.0, 540.0), (0.15, 980.0)])
    u = (t - 0.15) / 0.85
    base = 980.0 * (0.34 ** u)
    vib = 1.0 + 0.03 * math.sin(2.0 * math.pi * 6.5 * t) * min(1.0, u * 2.5)
    return base * vib


def amp_at(t):
    return seq(t, [
        (0.00, 0.00),
        (0.05, 0.22),
        (0.12, 0.42),
        (0.22, 0.88),
        (0.34, 1.00),
        (0.52, 0.78),
        (0.72, 0.38),
        (0.88, 0.14),
        (1.00, 0.00),
    ])


def formant_at(t):
    f1 = seq(t, [
        (0.00, 340.0), (0.10, 400.0), (0.20, 560.0),
        (0.34, 1120.0), (0.52, 880.0), (1.00, 500.0),
    ])
    f2 = seq(t, [
        (0.00, 1080.0), (0.10, 1550.0), (0.20, 2680.0),
        (0.34, 1680.0), (0.52, 1280.0), (1.00, 920.0),
    ])
    f3 = seq(t, [
        (0.00, 2300.0), (0.20, 3300.0), (0.40, 2800.0), (1.00, 2150.0),
    ])
    bw1 = seq(t, [(0.00, 70.0), (0.14, 95.0), (0.40, 120.0), (1.00, 90.0)])
    bw2 = seq(t, [(0.00, 90.0), (0.20, 150.0), (1.00, 120.0)])
    return f1, bw1, f2, bw2, f3, 190.0


def synth():
    r1, r2, r3 = Pole2(), Pole2(), Pole2()
    hp_x = 0.0
    hp_y = 0.0
    phase = 0.0
    g_prev = 0.0
    rs = 0xA5C3F1
    out = []
    for i in range(N):
        t = i / float(N - 1)
        f0 = f0_at(t)
        f1, bw1, f2, bw2, f3, bw3 = formant_at(t)
        r1.tune(f1, bw1)
        r2.tune(f2, bw2)
        r3.tune(f3, bw3)
        phase += f0 / FS
        if phase >= 1.0:
            phase -= 1.0
        te = 0.40
        g = math.sin(math.pi * phase / te) ** 2 if phase < te else 0.0
        dg = g - g_prev
        g_prev = g
        rs = rng_step(rs)
        nse = (rs / 2147483648.0) - 1.0
        breath = 0.05 + 0.16 * t
        x = dg * 3.1 + nse * breath * 0.18
        y = 0.52 * r1.tick(x) + 0.36 * r2.tick(x) + 0.12 * r3.tick(x)
        hp = y - hp_x + 0.995 * hp_y
        hp_x = y
        hp_y = hp
        out.append(hp * amp_at(t))
    peak = max(abs(v) for v in out) or 1.0
    return [v * 0.92 / peak for v in out]


def to_i8(samples):
    return [max(-127, min(127, int(round(v * 127.0)))) for v in samples]


def write_inc(path, data):
    lines = [
        "/* generated by app_tone_meow.py — 16 kHz signed 8-bit meow */",
        "static const int8_t s_meow[] = {",
    ]
    row = []
    for i, v in enumerate(data):
        row.append("%4d" % v)
        if len(row) == 16:
            lines.append("    " + ",".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ",".join(row) + ",")
    lines.append("};")
    lines.append("")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def write_wav(path, data):
    with wave.open(path, "w") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(FS)
        frames = b"".join(int(v * 30000).to_bytes(2, "little", signed=True)
                          for v in data)
        w.writeframes(frames)


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    raw = synth()
    write_inc(os.path.join(here, "app_tone_meow.inc"), to_i8(raw))
    write_wav("/tmp/app_tone_meow.wav", raw)


if __name__ == "__main__":
    main()
