idf_component_register(
    SRCS "main.c"
         "app_ui.c"
         "app_i18n.c"
         "assets/station_scene.c"
         "assets/navigation_icons.c"
         "assets/farm_crops.c"
         "fonts/app_font_zh_14.c"
         "fonts/app_font_zh_20.c"
         "ui_pixel.c"
         "ui_pixel_math.c"
         "game/game_state.c"
         "game/game_content.c"
         "services/save_service.c"
         "services/app_persistence_esp.c"
         "services/clock_service_esp.c"
         "services/telemetry_esp.c"
         "demo_display.c"
         "demo_button.c"
         "demo_audio.c"
         "demo_battery.c"
    INCLUDE_DIRS "."
    REQUIRES bsp
)
