idf_component_register(
    SRCS "main.c"
         "ui_pixel.c"
         "ui_pixel_math.c"
         "ble_filter.c"
         "app_logic.c"
         "app_prefs.c"
         "app_i18n.c"
         "app_time.c"
         "app_ui.c"
         "app_tone.c"
         "app_notif.c"
         "app_shell.c"
         "app_lock.c"
         "app_home.c"
         "app_settings.c"
         "app_wifi.c"
         "app_ble.c"
         "app_tune.c"
         "app_ancs.c"
         "app_web.c"
         "app_hw.c"
         "app_logs.c"
         "app_wx.c"
         "app_totp.c"
         "walkie_codec.c"
         "walkie.c"
         "walkie_ble.c"
         "walkie_rtc.c"
         "app_rtc.c"
         "app_walkie.c"
         "qrcode.c"
         "fonts/lv_font_cjk_12.c"
    INCLUDE_DIRS "."
    REQUIRES bsp nvs_flash esp_netif lwip esp_http_server esp_https_server
             esp_app_format spi_flash driver bt
    EMBED_TXTFILES "certs/servercert.pem" "certs/prvtkey.pem"
)
